# Generated by Django 5.0.2 on 2026-04-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ESPERA', 'En espera'), ('APROBADA', 'Aprobada'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('primera_entrada_mexico', models.BooleanField(default=False, verbose_name='Primera entrada a México')),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='embarcaciones.embarcacion')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Historial de solicitud',
                'verbose_name_plural': 'Historial de solicitudes',
                'db_table': 'solicitud_historial',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
