# Generated by Django 5.0.2 on 2026-05-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo de rechazo'),
        ),
    ]
