# Generated by Django 5.0.2 on 2026-04-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_barco', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Tipo de barco',
                'verbose_name_plural': 'Tipos de barco',
                'db_table': 'tipo_barco',
                'ordering': ['tipo_barco'],
            },
        ),
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bote', models.CharField(max_length=50)),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('manga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarcaciones', to='clientes.cliente')),
                ('tipo_barco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarcaciones', to='embarcaciones.tipobarco')),
            ],
            options={
                'verbose_name': 'Embarcación',
                'verbose_name_plural': 'Embarcaciones',
                'db_table': 'embarcacion',
                'ordering': ['nombre_bote'],
            },
        ),
    ]
