# Generated by Django 5.0.2 on 2026-05-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='rol',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
