# Generated by Django 5.0.2 on 2026-05-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_administrador_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
