# Generated by Django 5.0.2 on 2026-05-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_administrador_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de asignación'),
        ),
    ]
