# Generated by Django 5.0.2 on 2026-05-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_administrador_fecha_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='fecha_asignacion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de asignación'),
        ),
    ]
