# Generated by Django 5.0.2 on 2026-04-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tam_maximo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_espacios', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('coordenada_x', models.DecimalField(decimal_places=6, max_digits=10)),
                ('coordenada_y', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'verbose_name': 'Muelle',
                'verbose_name_plural': 'Muelles',
                'db_table': 'muelle',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaTierra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.TextField()),
                ('color', models.CharField(default='#7ab648', max_length=7)),
                ('nombre', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Zona de tierra',
                'verbose_name_plural': 'Zonas de tierra',
                'db_table': 'zona_tierra',
            },
        ),
        migrations.CreateModel(
            name='EtiquetaMuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pos_y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('texto', models.CharField(max_length=80)),
                ('tamanio', models.PositiveIntegerField(default=14)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('muelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta', to='muelles.muelle')),
            ],
            options={
                'verbose_name': 'Etiqueta de muelle',
                'verbose_name_plural': 'Etiquetas de muelles',
                'db_table': 'etiqueta_muelle',
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('pos_x', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rotacion', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('es_pasillo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('muelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='muelles.muelle')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacio',
                'ordering': ['muelle', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.UniqueConstraint(condition=models.Q(('es_pasillo', False)), fields=('muelle', 'numero'), name='uq_espacio_muelle_numero'),
        ),
    ]
